# Generated by Django 3.0 on 2020-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='txt',
            field=models.FileField(null=True, upload_to='data_files/'),
        ),
    ]
