# Generated by Django 3.0 on 2020-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20200618_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='txt_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
